
name: Build and Test

on:
  push:
  pull_request:

jobs:

  build-and-test:
    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0

